### ISSUE TITLE
[BUG]启用Api key后，scan的url会覆盖掉以前存在的

### ISSUE THREAD

**Issue by dengrandpa** [ycvk/deeplx-local#11]
autoScan ->  processUrls， 
processUrls中直接使用的os.WriteFile("url.txt", []byte(strings.Join(urls, "\n")), 0600)，此处url被覆盖了

**Comment by ycvk** [comment]
问题在`processUrls()`方法里会全量保存`url.txt`, 保存文件逻辑单独提出来了, 修了下, 应该没问题了

**Comment by dengrandpa** [comment]
谢谢
