### ISSUE TITLE
沉浸式翻译有概率卡死

### ISSUE THREAD

**Issue by maizhouzi** [ycvk/deeplx-local#16]
![image](https://github.com/ycvk/deeplx-local/assets/66940944/027ebc52-843f-42d1-b21c-96db8c669268)
![image](https://github.com/ycvk/deeplx-local/assets/66940944/21611045-60fa-4826-afbb-5e02c9379c1c)
目前用的是v0.1.6版本，无论是在vps上用docker部署还是在本地部署，在翻译的文章比较长的情况下，比较容易出现卡死的现象，具体表现为如图所示，正常情况下响应时间在1秒以下，在某个点开始就会响应时间持续长于5秒，沉浸式翻译返回API Error，同时CPU持续占用100%，并且不会随着翻译超时而下降。

**Comment by ycvk** [comment]
在修了在修了，下午提交的一版代码里，把没写好的对象池那里的实现也勾上提交上了，造成这种错误

**Comment by ycvk** [comment]
ok了，docker镜像和二进制文件都打包完了[Release](https://github.com/ycvk/deeplx-local/releases)
