### ISSUE TITLE
win

### ISSUE THREAD

**Issue by yours57** [ycvk/deeplx-local#21]
最新版取消有图标的windows版本了吗？

**Comment by ycvk** [comment]
https://github.com/ycvk/deeplx-local/releases/tag/windows-v0.1.9

其实win版本一直没加上带图标的exe去编译，刚加了一个，现在有了
![fc225e2036e78cf1e62e2817670ac663.png](https://i2.mjj.rip/2024/06/04/fc225e2036e78cf1e62e2817670ac663.png)

**Comment by yours57** [comment]
已下载，谢谢开发者
