### ISSUE TITLE
win-exe图标问题

### ISSUE THREAD

**Issue by renaissancecode** [ycvk/deeplx-local#36]
发现在v0.2.4-windows中，没有图标但有窗口，而在v0.2.3中，有图标没有窗口。

能否统一一下图标和窗口的显示：点击exe启动窗口，点击最小化显示托盘图标，点击托盘图标显示窗口，右键托盘图标退出。

感谢！虽然目前已经非常好用了！

**Comment by ycvk** [comment]
靠，听起来我初步估计是我合并分支的时候合并错了，等我看看
