### ISSUE TITLE
如何静默启动deeplx.exe

### ISSUE THREAD

**Issue by pennbay** [ycvk/deeplx-local#4]
如题，在windows中启动deeplx.exe后，会弹出命令行窗口，若用户关闭此窗口，则deeplx本地服务也被停止。
是否有办法静默启动deeplx程序，不弹出命令行窗口或最小化到托盘运行。

**Comment by ycvk** [comment]
可以，你的意思是就像很多服务那样，打开后没有界面，直接只有一个在右下角托盘里的小图标是吧，小图标点关闭了服务就关闭了，我单独开一个windows分支实现下试试

**Comment by ycvk** [comment]
ok了，下载试试呢：
https://github.com/ycvk/deeplx-local/releases/tag/windows-v0.1.2


现在打开exe只会在托盘有一个小图标![2fa59a5c188a7e02041948d7b6918e83.png](https://i.mji.rip/2024/05/08/2fa59a5c188a7e02041948d7b6918e83.png)

不想用了想关了，点一下图标，点`quit`就行了

**Comment by ycvk** [comment]
> > ok了，下载试试呢： https://github.com/ycvk/deeplx-local/releases/tag/windows-v0.1.2
> > 现在打开exe只会在托盘有一个小图标![2fa59a5c188a7e02041948d7b6918e83.png](https://camo.githubusercontent.com/78b0a864b0dcbf6ec8ba40fa9eeef5c5c0cd6206d6282afac4e902640e98d4e0/68747470733a2f2f692e6d6a692e7269702f323032342f30352f30382f32666135396135633138386137653032303431393438643762363931386538332e706e67)
> > 不想用了想关了，点一下图标，点`quit`就行了
> 
> windows-v0.2.1取消托盘图标了吗？

没有吧，我看Release里编译过了啊，https://github.com/ycvk/deeplx-local/releases/tag/windows-v0.2.1
在Release里往下翻能看到
