### ISSUE TITLE
不自动替换失效的接口地址

### ISSUE THREAD

**Issue by axdlee** [ycvk/deeplx-local#8]
docker安装后，不重启的情况下，不会不自动替换失效的接口地址。只有docker重启后才自动筛选到可用的接口。
而有的接口不一定在什么时候会失效。

**Comment by ycvk** [comment]
已支持此功能，现在在请求失败的情况下，会自动标记不可用的url了，会在goroutine中每分钟定时重试不可用的url，达到最大次数仍然不可用就永久不会再使用此url了
